name: Pro Native Compiler
run-name: Compile ${{ inputs.appName }}
on:
  workflow_dispatch:
    inputs:
      id: { required: true, type: string }
      appName: { required: true, type: string }
      packageName: { required: true, type: string }
      versionCode: { required: true, type: string }
      versionName: { required: true, type: string }
      iconUrl: { required: true, type: string }
      webhookUrl: { required: true, type: string }
      uploadUrl: { required: true, type: string }
      logUrl: { required: true, type: string }
      mode: { required: true, type: string }
      url: { required: false, type: string }
      projectZip: { required: false, type: string }
      buildFormat: { required: false, type: string, default: 'apk' }
      minSdk: { required: false, type: string, default: '24' }
      targetSdk: { required: false, type: string, default: '34' }
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - name: Init Engine
        run: |
          RAW_NAME="${{ github.event.repository.name }}"
          PREFIX="[$(echo "$RAW_NAME" | sed 's/-/ /g')]"
          echo "PREFIX=$PREFIX" >> $GITHUB_ENV
          curl -s -X POST -H "Content-Type: application/json" -d "{\"id\": \"${{ inputs.id }}\", \"log\": \"$PREFIX Memulai Mesin Kompilasi Cloud...\"}" "${{ inputs.logUrl }}" > /dev/null
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          
      - name: Persistent Keystore Setup
        run: |
          curl -s -X POST -H "Content-Type: application/json" -d "{\"id\": \"${{ inputs.id }}\", \"log\": \"${{ env.PREFIX }} Memverifikasi sertifikat kriptografi...\"}" "${{ inputs.logUrl }}" > /dev/null
          if [ ! -f "appstudio.keystore" ]; then
            keytool -genkeypair -v -keystore appstudio.keystore -alias appstudio -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=AppStudio, OU=AppStudio, O=AppStudio, L=Bali, ST=Bali, C=ID" -storepass appstudio2026 -keypass appstudio2026 > /dev/null 2>&1
            git config user.name "Build Engine"
            git config user.email "engine@appbuilder.id"
            git add app
